const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cal=[[15,280],[16,297],[17,310],[18,333],[19,376],[20,393],[21,405],[22,437],[25,502]];
let knob=19,roast="medium",rot=-(knob%10)*36,drag=false,last=0,acc=0;
const tastes=[["sour","🍋 날카로운 신맛"],["bitter","☕ 쓴맛 / 로스티함"],["dry","🌿 떫음 / 건조감"],["thin","💧 묽음 / 밋밋함"],["heavy","🪵 무거움 / 답답함"],["hollow","🕳️ 빈 맛 / 짧은 피니시"],["sweet","🍯 단맛 / 균형감"]];
const rc={light:[92,95,1.8,2.3],medium:[89,92,1.5,1.8],mediumdark:[88,91,1.4,1.7],dark:[86,89,1.3,1.6]};
function micron(p){for(let i=0;i<cal.length-1;i++){let a=cal[i],b=cal[i+1];if(p===a[0])return a[1];if(p>a[0]&&p<b[0])return Math.round(a[1]+(p-a[0])*(b[1]-a[1])/(b[0]-a[0]));}let a=cal.at(-2),b=cal.at(-1);return Math.round(a[1]+(p-a[0])*(b[1]-a[1])/(b[0]-a[0]));}
function kp(p){return Math.floor(p/10)+"+"+(p%10)}
function state(v){return v===0?"없음":v<=2?"아주 약함":v<=4?"약함":v<=6?"중간":v<=8?"강함":"매우 강함"}
function render(){ $("#knobText").textContent=kp(knob);$("#umText").textContent=micron(knob)+" µm";let d=+$("#dose").value,y=+$("#yield").value;$("#ratioText").textContent=d&&y?"1:"+(y/d).toFixed(2):"-";$("#knob").style.transform="translateX(-50%)"}
function build(){$("#dial").innerHTML="";tastes.forEach(([id,n],i)=>$("#sliders").insertAdjacentHTML("beforeend",`<div class="flavor"><div class="fhead"><span>${n}</span><span class="state" id="${id}S"></span></div><input id="${id}" type="range" min="0" max="10" value="${id==="sweet"?5:0}"></div>`));}
function refresh(){tastes.forEach(([id])=>$("#"+id+"S").textContent=state(+$("#"+id).value))}
$$(".roasts button").forEach(b=>b.onclick=()=>{$$(".roasts button").forEach(x=>x.classList.remove("on"));b.classList.add("on");roast=b.dataset.roast});
$$(".quick button").forEach(b=>b.onclick=()=>{$$(".quick button").forEach(x=>x.classList.remove("on"));b.classList.add("on");tastes.forEach(([id])=>$("#"+id).value=id==="sweet"?3:0);if(b.dataset.preset==="sour"){sour.value=8;thin.value=5;hollow.value=4}if(b.dataset.preset==="bitter"){bitter.value=8;dry.value=5}if(b.dataset.preset==="mixed"){sour.value=7;bitter.value=7;dry.value=5}refresh()});
document.addEventListener("input",e=>{if(e.target.matches("input")){refresh();render()}});
function ang(e){let r=$("#knob").getBoundingClientRect();return Math.atan2(e.clientY-(r.top+r.height/2),e.clientX-(r.left+r.width/2))*180/Math.PI}
$("#knob").onpointerdown=e=>{drag=true;last=ang(e);$("#knob").setPointerCapture?.(e.pointerId)};
$("#knob").onpointermove=e=>{if(!drag)return;let a=ang(e),d=a-last;if(d>180)d-=360;if(d<-180)d+=360;last=a;acc+=d;rot+=d;while(acc>=18){knob=Math.max(0,knob-.5);acc-=18}while(acc<=-18){knob+=.5;acc+=18}render()};
$("#knob").onpointerup=$("#knob").onpointercancel=()=>{drag=false;acc=0};
$("#analyze").onclick=()=>{let d=+dose.value,y=+yield.value,t=+time.value,tmp=+temp.value;if(!d||!y||!t||!tmp)return alert("현재 샷 정보를 확인해줘.");let r=y/d,c=rc[roast],S=+sour.value,B=+bitter.value,D=+dry.value,T=+thin.value,H=+heavy.value,O=+hollow.value,W=+sweet.value,u=S+T*.8+O*.7+(t<24?3:0)+(r<c[2]?2:0),o=B+D*1.15+H*.5+(t>31?3:0)+(r>c[3]?2:0),mixed=S>=4&&(B>=4||D>=4),tar=knob,b="미세조정",h="한 변수만 미세 조정",why="한쪽 결점이 뚜렷하지 않아 작은 조정이 좋습니다.",steps=["퍽 균일성과 흐름 확인","가장 강한 결점 방향으로 한 변수만 조정"];if(W>=7&&Math.max(S,B,D,T,H,O)<=3){b="균형 좋음";h="지금 세팅 그대로";why="단맛과 균형이 좋고 결점 신호가 낮습니다.";steps=["아무것도 바꾸지 않기","오늘 기준 샷으로 저장"]}else if(mixed){b="불균일 추출 의심";why="신맛과 쓴맛/떫음이 함께 강합니다.";steps=["WDT·분배·수평 탬핑 확인","그다음 노브 0.5~1칸만 조정"]}else if(u>o+2){tar=knob-1;b="저추출 쪽";h="1칸 곱게";why="신맛·묽음·빈 맛과 빠른 흐름이 저추출 쪽입니다.";steps=["FINE 방향 1칸","그래도 비면 추출량 +2g","마지막에 온도 +0.5~1°C"]}else if(o>u+2){tar=knob+1;b="과다추출 쪽";h="1칸 굵게";why="쓴맛·떫음·건조감과 느린 흐름이 과다추출 쪽입니다.";steps=["COARSE 방향 1칸","그래도 거칠면 추출량 -2g","마지막에 온도 -0.5~1°C"]}badge.textContent=b;headline.textContent=h;cur.textContent=kp(knob);target.textContent=kp(tar);reason.textContent=why;plan.innerHTML=steps.map((x,i)=>`<div><b>${i+1}.</b> ${x}</div>`).join("");result.classList.remove("hidden");result.scrollIntoView({behavior:"smooth"})};
$("#saveShot").onclick=()=>{let H=JSON.parse(localStorage.getItem("shots")||"[]");H.unshift({k:knob,d:+dose.value,y:+yield.value,t:+time.value,tmp:+temp.value});localStorage.setItem("shots",JSON.stringify(H.slice(0,6)));showHist()};
function showHist(){let H=JSON.parse(localStorage.getItem("shots")||"[]");history.innerHTML=H.map(x=>`<div class="hist"><b>${kp(x.k)}</b> · ${x.d}→${x.y}g · ${x.t}s · ${x.tmp}°C</div>`).join("")}
$("#reset").onclick=()=>{knob=19;rot=-324;dose.value=20.5;yield.value=34;time.value=27;temp.value=90;tastes.forEach(([id])=>$("#"+id).value=id==="sweet"?5:0);result.classList.add("hidden");refresh();render()};
build();refresh();render();showHist();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});